import React, { useState } from 'react';

// Simple helper to parse basic markdown lists and bold text
const formatText = (text) => {
    if (!text) return null;
    const lines = text.split('\n');

    return lines.map((line, index) => {
        // Check if line is a bullet point
        if (line.trim().startsWith('* ') || line.trim().startsWith('- ')) {
            return <li key={index}>{line.replace(/^[\*|\-]\s/, '')}</li>;
        }
        // Check if line is a numbered list
        if (/^\d+\.\s/.test(line.trim())) {
            return <li key={index}>{line.replace(/^\d+\.\s/, '')}</li>;
        }

        // Identify all-caps headings like 'OVERVIEW'
        const trimmed = line.trim();
        if (trimmed.length > 0 && trimmed.length < 40 && /^[A-Z\s]+$/.test(trimmed)) {
            return <h4 key={index} style={{ marginTop: '1.2rem', marginBottom: '0.4rem', color: 'var(--text-primary)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>{trimmed}</h4>;
        }

        if (trimmed === '') return <br key={index} />;
        return <p key={index} style={{ marginBottom: '0.5rem', lineHeight: '1.5' }}>{line}</p>;
    });
};

const formatTime = (seconds) => {
    const min = Math.floor(seconds / 60);
    const sec = Math.floor(seconds % 60);
    return `[${min.toString().padStart(2, '0')}:${sec.toString().padStart(2, '0')}]`;
};

const renderTranscript = (transcriptData) => {
    if (!transcriptData) return 'No transcript available.';

    try {
        const parsed = JSON.parse(transcriptData);
        if (Array.isArray(parsed)) {
            return (
                <div className="transcript-list" style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                    {parsed.map((chunk, idx) => (
                        <div key={idx} style={{ display: 'flex', gap: '1rem', lineHeight: '1.5' }}>
                            <span style={{ color: 'var(--primary-color)', fontWeight: '500', flexShrink: 0 }}>
                                {formatTime(chunk.start_time_in_seconds || 0)}
                            </span>
                            <span style={{ color: 'var(--text-secondary)' }}>
                                {chunk.text}
                            </span>
                        </div>
                    ))}
                </div>
            );
        }
    } catch (e) {
        // Fallback for older string transcripts
    }

    return <div style={{ whiteSpace: 'pre-wrap', lineHeight: '1.5' }}>{transcriptData}</div>;
};

function ResultDetail({ result }) {
    const [showTranscript, setShowTranscript] = useState(false);

    // Q&A State
    const [question, setQuestion] = useState('');
    const [qaHistory, setQaHistory] = useState([]);
    const [asking, setAsking] = useState(false);
    const [qaError, setQaError] = useState('');

    const handleAskQuestion = async (e) => {
        e.preventDefault();
        if (!question.trim()) return;

        setAsking(true);
        setQaError('');

        const currentQuestion = question;
        setQuestion(''); // clear input immediately

        // Optimistically add to history
        const tempId = Date.now();
        setQaHistory(prev => [...prev, { id: tempId, q: currentQuestion, a: null, loading: true }]);

        try {
            const res = await fetch(`http://localhost:8000/api/analyses/${result.id}/question`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ question: currentQuestion }),
            });

            if (!res.ok) {
                const errData = await res.json();
                throw new Error(errData.detail || 'Failed to get answer');
            }

            const data = await res.json();

            setQaHistory(prev => prev.map(item =>
                item.id === tempId ? { ...item, a: data.answer, loading: false } : item
            ));
        } catch (err) {
            setQaHistory(prev => prev.filter(item => item.id !== tempId));
            setQaError(err.message);
        } finally {
            setAsking(false);
        }
    };

    if (!result) return null;

    return (
        <div className="card result-section">
            <h2>Results for: {result.video_title || 'Unknown Video'}</h2>
            <a
                href={result.youtube_url}
                target="_blank"
                rel="noopener noreferrer"
                style={{ color: 'var(--primary-color)', fontSize: '0.9rem', marginBottom: '1.5rem', display: 'block' }}
            >
                {result.youtube_url}
            </a>

            <div className="summary-content">
                <h3>AI Summary</h3>
                {/* Render summary safely without full markdown parser for simplicity, 
            interpreting lists properly if generated by LLM */}
                <div style={{ marginTop: '1rem', backgroundColor: 'rgba(0,0,0,0.1)', padding: '1.5rem', borderRadius: '8px' }}>
                    {formatText(result.summary)}
                </div>
            </div>

            <div className="transcript-section">
                <div
                    className="collapsible-header"
                    onClick={() => setShowTranscript(!showTranscript)}
                >
                    <span style={{ fontWeight: '600' }}>Full Transcript</span>
                    <span>{showTranscript ? '▲' : '▼'}</span>
                </div>

                <div className={`collapsible-content ${!showTranscript ? 'hidden' : ''}`}>
                    {renderTranscript(result.transcript)}
                </div>
            </div>

            <div className="qa-section">
                <hr className="divider" />
                <h3>Ask Questions About This Video</h3>

                <div className="qa-history">
                    {qaHistory.map((item) => (
                        <div key={item.id} className="qa-item">
                            <div className="qa-bubble user-bubble">
                                <strong>You:</strong> {item.q}
                            </div>
                            {item.loading ? (
                                <div className="qa-bubble ai-bubble loading-bubble">
                                    <div className="typing-dot"></div>
                                    <div className="typing-dot"></div>
                                    <div className="typing-dot"></div>
                                </div>
                            ) : (
                                <div className="qa-bubble ai-bubble plain-text-container-small">
                                    <strong>AI:</strong>
                                    <div style={{ marginTop: '0.5rem' }}>{formatText(item.a)}</div>
                                </div>
                            )}
                        </div>
                    ))}
                </div>

                <form onSubmit={handleAskQuestion} className="qa-form">
                    <input
                        type="text"
                        placeholder="e.g., What did the speaker say about X?"
                        value={question}
                        onChange={(e) => setQuestion(e.target.value)}
                        disabled={asking}
                    />
                    <button type="submit" disabled={asking || !question.trim()}>
                        Ask
                    </button>
                </form>
                {qaError && (
                    <div className="error-message">
                        <strong>Error:</strong> {qaError}
                    </div>
                )}
            </div>
        </div>
    );
}

export default ResultDetail;
